# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Maximal Overlap Discrete Wavelet Transform Wavelet Filter
#'
#' Compute the MODWT wavelet filter, which is just the regular wavelet
#' filter, divided by `sqrt(2)`. This function is used for the pyramid
#' algorithm used in `modwt`.
#'
#' @param filter A character string indicating the wavelet filter desired
#' @return Wavelet filter vector (a numeric vector)
#' @references
#' Percival, D. B. and A. T. Walden (2000) Wavelet Methods for Time Series Analysis, Cambridge
#' University Press.
#'
#' Wasilewski, F. (2008). Wavelet browser by pywavelets. Wavelet Properties Browser.
#' Retrieved November 17, 2022, from http://wavelets.pybytes.com/
#'
#' Gregory R. Lee, Ralf Gommers, Filip Wasilewski, Kai Wohlfahrt, Aaron O’Leary (2019).
#' PyWavelets: A Python package for wavelet analysis. Journal of Open Source Software,
#' 4(36), 1237, https://doi.org/10.21105/joss.01237.
#'
#' Olhede, S., &amp; Walden, A. T. (2004). The Hilbert spectrum via wavelet projections.
#' Proceedings of the Royal Society of London. Series A: Mathematical, Physical and
#' Engineering Sciences, 460(2044), 955–975. https://doi.org/10.1098/rspa.2003.1199
#'
#' Maheswaran, R., &amp; Khosa, R. (2012). Comparative study of different wavelets for
#' hydrologic forecasting. Computers &amp; Geosciences, 46, 284–295.
#' https://doi.org/10.1016/j.cageo.2011.12.015
#'
#' Daubechies, Ingrid. Ten Lectures on Wavelets. Society for Industrial and Applied Mathematics, 1992.
#'
#' Morris, Joel M, and Ravindra Peravali. “Minimum-Bandwidth Discrete-Time Wavelets.” Signal Processing 76,
#' no. 2 (July 1999): 181–93. https://doi.org/10.1016/S0165-1684(99)00007-9.
#'
#' Doroslovački, M.L. “On the Least Asymmetric Wavelets.” IEEE Transactions on Signal Processing 46,
#' no. 4 (April 1998): 1125–30. https://doi.org/10.1109/78.668562.
#'
#' Han, Bin. “Wavelet Filter Banks.” In Framelets and Wavelets: Algorithms, Analysis, and Applications,
#' 92–98. Applied and Numerical Harmonic Analysis. Cham, Switzerland: Birkhäuser, 2017.
#' https://doi.org/10.1007/978-3-319-68530-4_2.
#'
#' Vaidyanathan, P. P. & Hoang, P.-Q. Lattice structures for optimal design and robust implementation
#' of two-channel perfect-reconstruction QMF banks. IEEE Trans. Acoust. 36, 81–94 (1988).
#'
#' Wickerhauser, M. V. Adapted Wavelet Analysis from Theory to Software.
#' Adapted Wavelet Analysis from Theory to Software (A.K. Peters, 1994).
#' @keywords internal
wavelet_filter <- function(filter) {
    .Call(`_fastWavelets_wavelet_filter`, filter)
}

#' Maximal Overlap Discrete Wavelet Transform Scaling Filter
#'
#' Compute the MODWT scaling filter, which is just the regular wavelet
#' filter, divided by `sqrt(2)`. This function is used for the pyramid algorithm
#' used in `modwt`.
#'
#' @param filter A character string indicating the scaling filter desired
#' @return Scaling filter vector (a numeric vector)
#' @references
#' Percival, D. B. and A. T. Walden (2000) Wavelet Methods for Time Series Analysis, Cambridge
#' University Press.
#'
#' Wasilewski, F. (2008). Wavelet browser by pywavelets. Wavelet Properties Browser.
#' Retrieved November 17, 2022, from http://wavelets.pybytes.com/
#'
#' Gregory R. Lee, Ralf Gommers, Filip Wasilewski, Kai Wohlfahrt, Aaron O’Leary (2019).
#' PyWavelets: A Python package for wavelet analysis. Journal of Open Source Software,
#' 4(36), 1237, https://doi.org/10.21105/joss.01237.
#'
#' Olhede, S., &amp; Walden, A. T. (2004). The Hilbert spectrum via wavelet projections.
#' Proceedings of the Royal Society of London. Series A: Mathematical, Physical and
#' Engineering Sciences, 460(2044), 955–975. https://doi.org/10.1098/rspa.2003.1199
#'
#' Maheswaran, R., &amp; Khosa, R. (2012). Comparative study of different wavelets for
#' hydrologic forecasting. Computers &amp; Geosciences, 46, 284–295.
#' https://doi.org/10.1016/j.cageo.2011.12.015
#'
#' Daubechies, Ingrid. Ten Lectures on Wavelets. Society for Industrial and Applied Mathematics, 1992.
#'
#' Morris, Joel M, and Ravindra Peravali. “Minimum-Bandwidth Discrete-Time Wavelets.” Signal Processing 76,
#' no. 2 (July 1999): 181–93. https://doi.org/10.1016/S0165-1684(99)00007-9.
#'
#' Doroslovački, M.L. “On the Least Asymmetric Wavelets.” IEEE Transactions on Signal Processing 46,
#' no. 4 (April 1998): 1125–30. https://doi.org/10.1109/78.668562.
#'
#' Han, Bin. “Wavelet Filter Banks.” In Framelets and Wavelets: Algorithms, Analysis, and Applications,
#' 92–98. Applied and Numerical Harmonic Analysis. Cham, Switzerland: Birkhäuser, 2017.
#' https://doi.org/10.1007/978-3-319-68530-4_2.
#'
#' Vaidyanathan, P. P. & Hoang, P.-Q. Lattice structures for optimal design and robust implementation
#' of two-channel perfect-reconstruction QMF banks. IEEE Trans. Acoust. 36, 81–94 (1988).
#'
#' Wickerhauser, M. V. Adapted Wavelet Analysis from Theory to Software.
#' Adapted Wavelet Analysis from Theory to Software (A.K. Peters, 1994).
#'
#' @keywords internal
scaling_filter <- function(filter) {
    .Call(`_fastWavelets_scaling_filter`, filter)
}

#' @title Maximal Overlap Discrete Wavelet Transform
#' @param X An (N x 1) matrix or a vector
#' @param filter Filter name (see Details below) (string)
#' @param J Decomposition level (integer, 1 < J < N/2)
#' @details
#' The argument `filter` can take one of the following values:
#'
#' c('bl7', 'bl9', 'bl10',
#' 'beyl',
#' 'coif1', 'coif2', 'coif3', 'coif4', 'coif5',
#' 'db1', 'db2', 'db3', 'db4', 'db5', 'db6', 'db7', 'db8', 'db9', 'db10', 'db11', 'db12',
#' 'db13', 'db14', 'db15', 'db16', 'db17', 'db18', 'db19', 'db20', 'db21', 'db22', 'db23',
#' 'db24', 'db25', 'db26', 'db27', 'db28', 'db29', 'db30', 'db31', 'db32', 'db33',
#' 'db34', 'db35', 'db36', 'db37', 'db38', 'db39', 'db40', 'db41', 'db42', 'db43', 'db44', 'db45',
#' 'fk4', 'fk6', 'fk8', 'fk14', 'fk18', 'fk22',
#' 'han2_3', 'han3_3', 'han4_5', 'han5_5',
#' 'dmey',
#' 'mb4_2', 'mb8_2', 'mb8_3', 'mb8_4', 'mb10_3', 'mb12_3', 'mb14_3', 'mb16_3', 'mb18_3', 'mb24_3', 'mb32_3',
#' 'sym2', 'sym3', 'sym4', 'sym5', 'sym6', 'sym7', 'sym8', 'sym9', 'sym10', 'sym11', 'sym12', 'sym13', 'sym14',
#' 'sym15', 'sym16', 'sym17', 'sym18', 'sym19', 'sym20', 'sym21', 'sym22', 'sym23', 'sym24', 'sym25', 'sym26', 'sym27',
#' 'sym28', 'sym29', 'sym30', 'sym31', 'sym32', 'sym33', 'sym34', 'sym35', 'sym36', 'sym37', 'sym38', 'sym39', 'sym40',
#' 'sym41', 'sym42', 'sym43', 'sym44', 'sym45',
#' 'vaid',
#' 'la8', 'la10', 'la12', 'la14', 'la16', 'la18', 'la20')
#' @references
#' Percival, D. B. and A. T. Walden (2000) Wavelet Methods for Time Series Analysis, Cambridge
#' University Press.
#' @export
modwt <- function(X, filter, J) {
    .Call(`_fastWavelets_modwt`, X, filter, J)
}

#' MODWT Scaling Coefficients
#'
#' Compute the scaling coefficients. This function should not be called by end users.
#' If you want to obtain the MODWT scaling coefficient for a given filter and
#' decomposition level, please use `modwt_scaling_coefs`.
#'
#' @param X An (N x 1) matrix or a vector
#' @param filter A character string indicating the desired filter
#' @param j The decomposition level \[integer\]
#' @details This is an internal function used by `atrous_dwt`.
#' The argument `filter` can take one of the following values:
#'
#' c('bl7', 'bl9', 'bl10',
#' 'beyl',
#' 'coif1', 'coif2', 'coif3', 'coif4', 'coif5',
#' 'db1', 'db2', 'db3', 'db4', 'db5', 'db6', 'db7', 'db8', 'db9', 'db10', 'db11', 'db12',
#' 'db13', 'db14', 'db15', 'db16', 'db17', 'db18', 'db19', 'db20', 'db21', 'db22', 'db23',
#' 'db24', 'db25', 'db26', 'db27', 'db28', 'db29', 'db30', 'db31', 'db32', 'db33',
#' 'db34', 'db35', 'db36', 'db37', 'db38', 'db39', 'db40', 'db41', 'db42', 'db43', 'db44', 'db45',
#' 'fk4', 'fk6', 'fk8', 'fk14', 'fk18', 'fk22',
#' 'han2_3', 'han3_3', 'han4_5', 'han5_5',
#' 'dmey',
#' 'mb4_2', 'mb8_2', 'mb8_3', 'mb8_4', 'mb10_3', 'mb12_3', 'mb14_3', 'mb16_3', 'mb18_3', 'mb24_3', 'mb32_3',
#' 'sym2', 'sym3', 'sym4', 'sym5', 'sym6', 'sym7', 'sym8', 'sym9', 'sym10', 'sym11', 'sym12', 'sym13', 'sym14',
#' 'sym15', 'sym16', 'sym17', 'sym18', 'sym19', 'sym20', 'sym21', 'sym22', 'sym23', 'sym24', 'sym25', 'sym26', 'sym27',
#' 'sym28', 'sym29', 'sym30', 'sym31', 'sym32', 'sym33', 'sym34', 'sym35', 'sym36', 'sym37', 'sym38', 'sym39', 'sym40',
#' 'sym41', 'sym42', 'sym43', 'sym44', 'sym45',
#' 'vaid',
#' 'la8', 'la10', 'la12', 'la14', 'la16', 'la18', 'la20')
#' @return An (N x 1) matrix scaling coefficients
#' @references
#' Percival, D. B. and A. T. Walden (2000) Wavelet Methods for Time Series Analysis, Cambridge
#' University Press.
#' @keywords internal
scaling_coefs <- function(X, filter, j) {
    .Call(`_fastWavelets_scaling_coefs`, X, filter, j)
}

#' MODWT Wavelet Coefficients
#'
#' Compute the wavelet coefficients. This function should not be called by end users.
#' If you want to obtain the MODWT wavelet coefficient for a given filter and
#' decomposition level, please use `modwt_wavelet_coefs`.
#'
#' @param X An (N x 1) matrix or a vector
#' @param filter A character string indicating the desired filter
#' @param j The decomposition level \[integer\]
#' @details This is an internal function used by `atrous_dwt`.
#' The argument `filter` can take one of the following values:
#'
#' c('bl7', 'bl9', 'bl10',
#' 'beyl',
#' 'coif1', 'coif2', 'coif3', 'coif4', 'coif5',
#' 'db1', 'db2', 'db3', 'db4', 'db5', 'db6', 'db7', 'db8', 'db9', 'db10', 'db11', 'db12',
#' 'db13', 'db14', 'db15', 'db16', 'db17', 'db18', 'db19', 'db20', 'db21', 'db22', 'db23',
#' 'db24', 'db25', 'db26', 'db27', 'db28', 'db29', 'db30', 'db31', 'db32', 'db33',
#' 'db34', 'db35', 'db36', 'db37', 'db38', 'db39', 'db40', 'db41', 'db42', 'db43', 'db44', 'db45',
#' 'fk4', 'fk6', 'fk8', 'fk14', 'fk18', 'fk22',
#' 'han2_3', 'han3_3', 'han4_5', 'han5_5',
#' 'dmey',
#' 'mb4_2', 'mb8_2', 'mb8_3', 'mb8_4', 'mb10_3', 'mb12_3', 'mb14_3', 'mb16_3', 'mb18_3', 'mb24_3', 'mb32_3',
#' 'sym2', 'sym3', 'sym4', 'sym5', 'sym6', 'sym7', 'sym8', 'sym9', 'sym10', 'sym11', 'sym12', 'sym13', 'sym14',
#' 'sym15', 'sym16', 'sym17', 'sym18', 'sym19', 'sym20', 'sym21', 'sym22', 'sym23', 'sym24', 'sym25', 'sym26', 'sym27',
#' 'sym28', 'sym29', 'sym30', 'sym31', 'sym32', 'sym33', 'sym34', 'sym35', 'sym36', 'sym37', 'sym38', 'sym39', 'sym40',
#' 'sym41', 'sym42', 'sym43', 'sym44', 'sym45',
#' 'vaid',
#' 'la8', 'la10', 'la12', 'la14', 'la16', 'la18', 'la20')
#' @return (N x 1) matrix of wavelet coefficients
#' @references
#' Percival, D. B. and A. T. Walden (2000) Wavelet Methods for Time Series Analysis, Cambridge
#' University Press.
#' @keywords internal
wavelet_coefs <- function(X, filter, j) {
    .Call(`_fastWavelets_wavelet_coefs`, X, filter, j)
}

