# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Compute the wavelet filter
#'
#' @param wavelet A character string indicating the wavelet filter desired
#' @return Wavelet filter vector
#' @references
#' Percival, D. B. and A. T. Walden (2000) Wavelet Methods for Time Series Analysis, Cambridge
#' University Press.
wavelet_filter <- function(wavelet) {
    .Call(`_fastWavelets_wavelet_filter`, wavelet)
}

#' Compute the scaling filter
#'
#' @param wavelet A character string indicating the scaling filter desired
#' @return Scaling filter vector
#' @references
#' Percival, D. B. and A. T. Walden (2000) Wavelet Methods for Time Series Analysis, Cambridge
#' University Press.
scaling_filter <- function(wavelet) {
    .Call(`_fastWavelets_scaling_filter`, wavelet)
}

#' Compute scaling coefficients
#'
#' @param X A vector
#' @param wavelet A character string indicating the scaling filter desired
#' @param j The decomposition level
#' @return Matrix of scaling coefficients
#' @references
#' Percival, D. B. and A. T. Walden (2000) Wavelet Methods for Time Series Analysis, Cambridge
#' University Press.
scaling_coefs <- function(X, wavelet, j) {
    .Call(`_fastWavelets_scaling_coefs`, X, wavelet, j)
}

#' Compute wavelet coefficients
#'
#' @param X A vector
#' @param wavelet A character string indicating the scaling filter desired
#' @param j The decomposition level
#' @return Matrix of wavelet coefficients
#' @references
#' Percival, D. B. and A. T. Walden (2000) Wavelet Methods for Time Series Analysis, Cambridge
#' University Press.
wavelet_coefs <- function(X, wavelet, j) {
    .Call(`_fastWavelets_wavelet_coefs`, X, wavelet, j)
}

