# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Computes the wavelet filter
#'
#' @param wavelet A character string indicating the wavelet filter desired
#' @return Wavelet filter vector
#' @export
wavelet_filter <- function(wavelet) {
    .Call(`_fastWavelets_wavelet_filter`, wavelet)
}

#' Computes the scaling filter
#'
#' @param wavelet A character string indicating the wavelet filter desired
#' @return Scaling filter vector
#' @export
scaling_filter <- function(wavelet) {
    .Call(`_fastWavelets_scaling_filter`, wavelet)
}

#' Computes scaling coefficients
#'
#' @param X A vector
#' @param wavelet A character string indicating the wavelet filter desired
#' @param j The decomposition level
#' @return Matrix of scaling coefficients
#' @export
scaling_coefs <- function(X, wavelet, j) {
    .Call(`_fastWavelets_scaling_coefs`, X, wavelet, j)
}

#' Computes wavelet coefficients
#'
#' @param X A vector
#' @param wavelet A character string indicating the wavelet filter desired
#' @param j The decomposition level
#' @return Matrix of wavelet coefficients
#' @export
wavelet_coefs <- function(X, wavelet, j) {
    .Call(`_fastWavelets_wavelet_coefs`, X, wavelet, j)
}

